OS=Linux
UADIR=/home1/06793/hongyu_5/iono_lab/mentor
COMPILER=ifortmpif90
# Local Makefile.def

localdefault: help # default target

DIR     = ${UADIR}

SCRIPTDIR = ${UADIR}/share/Scripts
LIBDIR    = ${UADIR}/src
RUNDIR    = ${UADIR}/run
BINDIR    = ${UADIR}/src
SHAREDIR  = ${UADIR}/share/Library/src
NOMPIDIR  = ${UADIR}/util/NOMPI/src
EMPIRICALIEDIR     = ${UADIR}/util/EMPIRICAL/srcIE
EMPIRICALUADIR     = ${UADIR}/util/EMPIRICAL/srcUA
DATAREADINDICESDIR = ${UADIR}/util/DATAREAD/srcIndices
EDYNAMICSDIR = ${UADIR}/util/EDYNAMICS
EMPIRICALAEPMDIR    = ${UADIR}/util/EMPIRICAL/srcAEPM
EMPIRICALEPMDIR    = ${UADIR}/util/EMPIRICAL/srcEPM
EMPIRICALEFVMDIR    = ${UADIR}/util/EMPIRICAL/srcEFVM
